org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.2.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

create_minecraft_version = 1.20.1
flywheel_minecraft_version = 1.20.1
gamestages_version_minecraft = 1.20.1
bookshelf_version_minecraft = 1.20.1

create_version = 6.0.5-191
flywheel_version = 1.0.4
ponder_version = 1.0.78
registrate_version = MC1.20-1.3.3
gamestages_version = 15.0.1
bookshelf_version = 20.1.6

mod_id=jackseconomy
mod_name=Jack's Economy CTNH Fork
mod_license=All-Rights-Reserved
mod_version=1.2.3
mod_group_id=me.khajiitos
mod_authors=Khajiitos, Flapjack24, moguang
mod_description=Adds various economy features to the game! Integrates with Create!